version: '2.3'

services:
  web:
    build:
      context: .
      dockerfile: "${DOCKERFILE}"
    environment:
      COMMCAREHQ_BOOTSTRAP: "yes"
      DEPENDENT_SERVICES: "couch3:5984 postgres:5432 redis:6379 elasticsearch:9200 minio:9980 kafka:9092"
      DOCKER_HQ_OVERLAY: "${DOCKER_HQ_OVERLAY}"
    privileged: true  # allows mount inside container
    command: [runserver]
    links:
      - postgres
      - couch3
      - redis
      - elasticsearch
      - elasticsearch2
      - kafka
      - zookeeper
      - minio
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ..:/mnt/commcare-hq-ro:ro
      - ${VOLUME_PREFIX}lib:/mnt/lib

  formplayer:
    extends:
      file: hq-compose.yml
      service: formplayer
    environment:
      WEB_HOST: "web"
    links:
      - postgres
      - couch3
      - redis
    expose:
      - 8010
    ports:
      - "8010:8010"

  postgres:
    extends:
      file: hq-compose-services.yml
      service: postgres

  couch3:
    extends:
      file: hq-compose-services.yml
      service: couch3

  redis:
    extends:
      file: hq-compose-services.yml
      service: redis

  elasticsearch:
    extends:
      file: hq-compose-services.yml
      service: elasticsearch

  elasticsearch2:
    extends:
      file: hq-compose-services.yml
      service: elasticsearch2

  zookeeper:
    extends:
      file: hq-compose-services.yml
      service: zookeeper

  kafka:
    extends:
      file: hq-compose-services.yml
      service: kafka

  minio:
    extends:
      file: hq-compose-services.yml
      service: minio
