########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/commcarehq/Deploy+Process#DeployProcess-DeployingVellumtoStaging
  - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  # - jls/sync-mixins-hard-fail # Jenny May 24
  - jls/migrate-MobileAuthKeyRecord-2 # Jenny May 16
  # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
  - fr/user-data-jit            # Farid September 2
  - sr/case-reindex-staging # Sravan Oct 14
  # - gh/improve-queueing-repeaters # Graham Oct 22
  - sr/es-alias # Sravan Nov 18
  - dmr/count-email-sends-bounces-by-domain  # Danny Dec 18
  - nh/dhis2/sqldataset_maps  # Norman Dec 18
  - nh/reminders  # Norman Jan 26
  - fr/ethiopian-date-widget-webapps                            # Farid Jan 29
  - smh/bulk-upload-web-users # Steph Feb 22
  - sr/geocoder  # Sravan Feb 25
  - nh/master+adil-uddin/feature/USH-462-HQ-Properties-Change  # Norman Mar 1
  - adil-uddin:feature/USH-606-conditional-alert-modal # Adil/Jenny Feb 1
  - adil-uddin:feature/USH-632-pagination-updates # Adil/Jenny Feb 10
  - adil-uddin:feature/USH-462-HQ-Properties-Change # Adil/Jenny Feb 17
  - mk/fhir/data-dictionary # MK Feb 26
  - mk/fhir/api-2 # MK Feb 26
  - mk/fhir/data-dictionary-upload-2 # MK Mar 9
  - nh/fhir/repeater  # Norman Mar 1
  - smh/modify_admin_role_display_web_invite_download # Steph Mar 2
  - kev/repeat-add-new-translation # Kevin Mar 2
  # - challabeehyv:consumer_user_poc # Farid March 11
  - jls/case-search-parent-props # Jenny March 15
  - smh/add-location-data-web-user-download # Steph Mar 15
  - gh/modify-project-performance-report # Graham March 15
  - ap/translation-update # Amit March 16
  - ap/escape-html-underscore # Amit March 16
submodules: {}
